/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant':            '#e1e3e4',
        'on-surface':                 '#191c1d',
        'secondary-fixed':            '#d8e2ff',
        'inverse-surface':            '#2e3132',
        'secondary':                  '#495e8a',
        'on-background':              '#191c1d',
        'surface-tint':               '#005ac2',
        'surface':                    '#f8f9fa',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'surface-dim':                '#d9dadb',
        'error':                      '#ba1a1a',
        'on-tertiary-container':      '#fffbff',
        'tertiary-container':         '#b75b00',
        'on-tertiary-fixed-variant':  '#723600',
        'on-primary-fixed':           '#001a42',
        'on-tertiary':                '#ffffff',
        'background':                 '#f8f9fa',
        'on-surface-variant':         '#424754',
        'inverse-on-surface':         '#f0f1f2',
        'secondary-container':        '#b6ccff',
        'tertiary-fixed':             '#ffdcc6',
        'tertiary-fixed-dim':         '#ffb786',
        'on-secondary':               '#ffffff',
        'on-primary-container':       '#fefcff',
        'surface-container-highest':  '#e1e3e4',
        'tertiary':                   '#924700',
        'primary':                    '#0058be',
        'on-error-container':         '#93000a',
        'primary-fixed':              '#d8e2ff',
        'secondary-fixed-dim':        '#b1c6f9',
        'outline-variant':            '#c2c6d6',
        'surface-container':          '#edeeef',
        'primary-container':          '#2170e4',
        'surface-container-lowest':   '#ffffff',
        'on-secondary-fixed':         '#001a42',
        'on-secondary-fixed-variant': '#304671',
        'on-secondary-container':     '#405682',
        'outline':                    '#727785',
        'inverse-primary':            '#adc6ff',
        'surface-bright':             '#f8f9fa',
        'on-primary-fixed-variant':   '#004395',
        'surface-container-low':      '#f3f4f5',
        'primary-fixed-dim':          '#adc6ff',
        'on-primary':                 '#ffffff',
        'surface-container-high':     '#e7e8e9',
        'on-tertiary-fixed':          '#311400',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}